### ISSUE TITLE
DarkSky secret Key expiration?

### ISSUE THREAD

**Issue by Dontorpedo** [austinkregel/nova-weather-cards#5]
Hi, does the secret key from darksky expire after a while?
the weathercard is asking after some days for a api key.. but it was allready saved.

thanks
Denis

**Comment by austinkregel** [comment]
By default the method this card uses to store data is the Laravel Cache via another package of mine called `laravel-data-store`; specifically it uses `rememberForever` to permanently store the data, until the cache gets cleared.

I'd like to implement another way to store the information (without migrations), but I haven't had the chance to yet. PR's are open, and I'll be more than happy to review any code changes pushed my way.

**Comment by austinkregel** [comment]
In order to swap out the way we store data we could either update with new methods, the [src/WeatherStore.php](https://github.com/austinkregel/nova-weather-cards/blob/master/src/WeatherStore.php) file, or we could update the [data store package](https://github.com/austinkregel/laravel-data-store) itself.
